"""Detections -> ObservedState. Fixtures are generated by the FORWARD annotate
geometry (generate_discard_slots / generate_meld_boxes_v2 / HAND / dora_slot),
so assembly must invert them exactly — no detector, no images needed."""
import numpy as np

from majsoul_eye.annotate import pipeline as P
from majsoul_eye.normalize import BoardRegion
from majsoul_eye.recognize.detector import Detection
from majsoul_eye.tiles import NAME_TO_ID

H = P.build_homographies(1920, 1080)
REGION = BoardRegion(0, 0, 1920, 1080)


def _det_from_poly(poly_original, tile):
    xs = [p[0] for p in poly_original]; ys = [p[1] for p in poly_original]
    return Detection(xyxy=(min(xs), min(ys), max(xs), max(ys)), tile=tile,
                     cls=NAME_TO_ID[tile], score=0.9,
                     poly=tuple((float(x), float(y)) for x, y in poly_original))


def _river_dets(seat, pais, sideways_idx=None):
    river = [{"pai": p, "riichi": i == sideways_idx, "tsumogiri": False}
             for i, p in enumerate(pais)]
    slots = P.generate_discard_slots(seat, river, H["H_full_inv"],
                                     sideways_idx=sideways_idx)
    return [_det_from_poly(s["poly_original"], s["tile"]) for s in slots]


def test_river_order_recovered_all_seats():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "5sr", "2s", "7p", "C", "3m"]       # 6 + 2 rows
    for seat in range(4):
        dets = _river_dets(seat, pais)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        np.random.shuffle(items)                                  # order must not matter
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.pai for t in tiles] == pais
        assert not any(t.sideways for t in tiles)


def test_river_sideways_riichi_detected():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "2s", "7p", "C", "3m"]
    for seat in range(4):
        dets = _river_dets(seat, pais, sideways_idx=2)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.sideways for t in tiles] == [i == 2 for i in range(len(pais))]


def test_river_hole_flags_violation():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    dets = _river_dets(0, ["1m", "9p", "E", "2s", "7p", "C", "3m"])
    del dets[3]                                                   # hole in row 0
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _assign_river(0, items)
    assert viol


def _meld_dets(seat, melds_gt):
    boxes = P.generate_meld_boxes_v2(seat, melds_gt, H["H_full_inv"])
    return [_det_from_poly(b["poly_original"], b["tile"]) for b in boxes]


def _gt(type_, tiles, called="", added="", from_seat_rel=0, seat=0):
    return {"type": type_, "tiles": tiles, "called_pai": called,
            "added_pai": added, "from_seat": (seat + from_seat_rel) % 4}


def test_meld_parse_all_kinds_all_seats():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    for seat in range(4):
        gt = [_gt("pon", ["P", "P", "P"], called="P", from_seat_rel=2, seat=seat),
              _gt("chi", ["4s", "5s", "6s"], called="5s", from_seat_rel=3, seat=seat)]
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(seat, gt)]
        melds, viol = _parse_melds(seat, items)
        assert viol == []
        assert [(m.type, m.from_rel, m.called_pai) for m in melds] == \
               [("pon", 2, "P"), ("chi", 3, "5s")]
        assert sorted(melds[0].tiles) == ["P", "P", "P"]


def test_meld_parse_kans():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    seat = 1
    gt = [_gt("ankan", ["5m", "5m", "5m", "5mr"], seat=seat),
          _gt("daiminkan", ["C", "C", "C", "C"], called="C", from_seat_rel=1, seat=seat),
          _gt("kakan", ["W", "W", "W", "W"], called="W", added="W",
              from_seat_rel=2, seat=seat)]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(seat, gt)]
    melds, viol = _parse_melds(seat, items)
    assert viol == []
    assert [m.type for m in melds] == ["ankan", "daiminkan", "kakan"]
    # ankan of fives MUST contain the red (only 4 copies exist incl. the red)
    assert sorted(melds[0].tiles) == ["5m", "5m", "5m", "5mr"]
    assert melds[1].from_rel == 1
    assert melds[2].from_rel == 2 and melds[2].added_pai == "W"


def test_meld_parse_flags_garbage():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    gt = [_gt("pon", ["P", "P", "P"], called="P", from_seat_rel=2, seat=0)]
    dets = _meld_dets(0, gt)[:-1]                     # drop one tile -> unparsable
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _parse_melds(0, items)
    assert viol


def test_meld_parse_rejects_ambiguous_strip():
    # pon(C from kamicha) + daiminkan(C from kamicha) renders a cell sequence
    # with TWO forward-consistent decompositions (needs 7 C's — game-illegal,
    # only reachable via detector noise; check_observed would also reject the
    # frame). The parser must refuse rather than silently pick one.
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    gt = [_gt("pon", ["C", "C", "C"], called="C", from_seat_rel=3, seat=0),
          _gt("daiminkan", ["C", "C", "C", "C"], called="C", from_seat_rel=3, seat=0)]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(0, gt)]
    melds, viol = _parse_melds(0, items)
    assert melds == [] and any("ambiguous" in v for v in viol)


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_"):
            fn()
    print("test_assemble OK")
