"""Detections -> ObservedState. Fixtures are generated by the FORWARD annotate
geometry (generate_discard_slots / generate_meld_boxes_v2 / HAND / dora_slot),
so assembly must invert them exactly — no detector, no images needed."""
import numpy as np

from majsoul_eye.annotate import pipeline as P
from majsoul_eye.normalize import BoardRegion
from majsoul_eye.recognize.detector import Detection
from majsoul_eye.tiles import NAME_TO_ID

H = P.build_homographies(1920, 1080)
REGION = BoardRegion(0, 0, 1920, 1080)


def _det_from_poly(poly_original, tile):
    xs = [p[0] for p in poly_original]; ys = [p[1] for p in poly_original]
    return Detection(xyxy=(min(xs), min(ys), max(xs), max(ys)), tile=tile,
                     cls=NAME_TO_ID[tile], score=0.9,
                     poly=tuple((float(x), float(y)) for x, y in poly_original))


def _river_dets(seat, pais, sideways_idx=None):
    river = [{"pai": p, "riichi": i == sideways_idx, "tsumogiri": False}
             for i, p in enumerate(pais)]
    slots = P.generate_discard_slots(seat, river, H["H_full_inv"],
                                     sideways_idx=sideways_idx)
    return [_det_from_poly(s["poly_original"], s["tile"]) for s in slots]


def test_river_order_recovered_all_seats():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "5sr", "2s", "7p", "C", "3m"]       # 6 + 2 rows
    for seat in range(4):
        dets = _river_dets(seat, pais)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        np.random.shuffle(items)                                  # order must not matter
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.pai for t in tiles] == pais
        assert not any(t.sideways for t in tiles)


def test_river_sideways_riichi_detected():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "2s", "7p", "C", "3m"]
    for seat in range(4):
        dets = _river_dets(seat, pais, sideways_idx=2)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.sideways for t in tiles] == [i == 2 for i in range(len(pais))]


def test_river_hole_flags_violation():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    dets = _river_dets(0, ["1m", "9p", "E", "2s", "7p", "C", "3m"])
    del dets[3]                                                   # hole in row 0
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _assign_river(0, items)
    assert viol


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_"):
            fn()
    print("test_assemble OK")
