"""Detections -> ObservedState. Fixtures are generated by the FORWARD annotate
geometry (generate_discard_slots / generate_meld_boxes_v2 / HAND / dora_slot),
so assembly must invert them exactly — no detector, no images needed."""
import numpy as np

from majsoul_eye.annotate import pipeline as P
from majsoul_eye.normalize import BoardRegion
from majsoul_eye.recognize.detector import Detection
from majsoul_eye.tiles import NAME_TO_ID

H = P.build_homographies(1920, 1080)
REGION = BoardRegion(0, 0, 1920, 1080)


def _det_from_poly(poly_original, tile):
    xs = [p[0] for p in poly_original]; ys = [p[1] for p in poly_original]
    return Detection(xyxy=(min(xs), min(ys), max(xs), max(ys)), name=tile, tile=tile,
                     cls=NAME_TO_ID[tile], score=0.9,
                     poly=tuple((float(x), float(y)) for x, y in poly_original))


def _river_dets(seat, pais, sideways_idx=None):
    river = [{"pai": p, "riichi": i == sideways_idx, "tsumogiri": False}
             for i, p in enumerate(pais)]
    slots = P.generate_discard_slots(seat, river, H["H_full_inv"],
                                     sideways_idx=sideways_idx)
    return [_det_from_poly(s["poly_original"], s["tile"]) for s in slots]


def test_river_order_recovered_all_seats():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "5sr", "2s", "7p", "C", "3m"]       # 6 + 2 rows
    for seat in range(4):
        dets = _river_dets(seat, pais)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        np.random.shuffle(items)                                  # order must not matter
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.pai for t in tiles] == pais
        assert not any(t.sideways for t in tiles)


def test_river_sideways_riichi_detected():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    pais = ["1m", "9p", "E", "2s", "7p", "C", "3m"]
    for seat in range(4):
        dets = _river_dets(seat, pais, sideways_idx=2)
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        tiles, viol = _assign_river(seat, items)
        assert viol == []
        assert [t.sideways for t in tiles] == [i == 2 for i in range(len(pais))]


def test_river_hole_flags_violation():
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    dets = _river_dets(0, ["1m", "9p", "E", "2s", "7p", "C", "3m"])
    del dets[3]                                                   # hole in row 0
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _assign_river(0, items)
    assert viol


def _meld_dets(seat, melds_gt):
    boxes = P.generate_meld_boxes_v2(seat, melds_gt, H["H_full_inv"])
    return [_det_from_poly(b["poly_original"], b["tile"]) for b in boxes]


def _gt(type_, tiles, called="", added="", from_seat_rel=0, seat=0):
    return {"type": type_, "tiles": tiles, "called_pai": called,
            "added_pai": added, "from_seat": (seat + from_seat_rel) % 4}


def test_meld_parse_all_kinds_all_seats():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    for seat in range(4):
        gt = [_gt("pon", ["P", "P", "P"], called="P", from_seat_rel=2, seat=seat),
              _gt("chi", ["4s", "5s", "6s"], called="5s", from_seat_rel=3, seat=seat)]
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(seat, gt)]
        melds, viol = _parse_melds(seat, items)
        assert viol == []
        assert [(m.type, m.from_rel, m.called_pai) for m in melds] == \
               [("pon", 2, "P"), ("chi", 3, "5s")]
        assert sorted(melds[0].tiles) == ["P", "P", "P"]


def test_meld_parse_kans():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    seat = 1
    gt = [_gt("ankan", ["5m", "5m", "5m", "5mr"], seat=seat),
          _gt("daiminkan", ["C", "C", "C", "C"], called="C", from_seat_rel=1, seat=seat),
          _gt("kakan", ["W", "W", "W", "W"], called="W", added="W",
              from_seat_rel=2, seat=seat)]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(seat, gt)]
    melds, viol = _parse_melds(seat, items)
    assert viol == []
    assert [m.type for m in melds] == ["ankan", "daiminkan", "kakan"]
    # ankan of fives MUST contain the red (only 4 copies exist incl. the red)
    assert sorted(melds[0].tiles) == ["5m", "5m", "5m", "5mr"]
    assert melds[1].from_rel == 1
    assert melds[2].from_rel == 2 and melds[2].added_pai == "W"


def test_meld_parse_rejects_illegal_kakan():
    # A stacked cell whose top tile is a DIFFERENT kind than the base (e.g. a
    # misdetected 2p on a 4p pon — seen on a real phone screenshot) is not a
    # legal kakan; the strip must be refused, not returned as a fantasy meld.
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    gt = [_gt("kakan", ["4p", "4p", "4p", "2p"], called="4p", added="2p",
              from_seat_rel=3, seat=0)]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(0, gt)]
    melds, viol = _parse_melds(0, items)
    assert melds == [] and viol


def test_meld_parse_flags_garbage():
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    gt = [_gt("pon", ["P", "P", "P"], called="P", from_seat_rel=2, seat=0)]
    dets = _meld_dets(0, gt)[:-1]                     # drop one tile -> unparsable
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _parse_melds(0, items)
    assert viol


def test_meld_parse_rejects_ambiguous_strip():
    # pon(C from kamicha) + daiminkan(C from kamicha) renders a cell sequence
    # with TWO forward-consistent decompositions (needs 7 C's — game-illegal,
    # only reachable via detector noise; check_observed would also reject the
    # frame). The parser must refuse rather than silently pick one.
    from majsoul_eye.recognize.assemble import _fw_points, _parse_melds
    gt = [_gt("pon", ["C", "C", "C"], called="C", from_seat_rel=3, seat=0),
          _gt("daiminkan", ["C", "C", "C", "C"], called="C", from_seat_rel=3, seat=0)]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in _meld_dets(0, gt)]
    melds, viol = _parse_melds(0, items)
    assert melds == [] and any("ambiguous" in v for v in viol)


def _hand_dets(pais, drawn=None):
    from majsoul_eye.coords import HAND
    dets = []
    for i, p in enumerate(pais):
        b = HAND.slot_box(i)
        dets.append(_det_from_poly(
            [[b.x0 * 1920, b.y0 * 1080], [b.x1 * 1920, b.y0 * 1080],
             [b.x1 * 1920, b.y1 * 1080], [b.x0 * 1920, b.y1 * 1080]], p))
    if drawn:
        b = HAND.slot_box(len(pais), is_tsumo=True)
        dets.append(_det_from_poly(
            [[b.x0 * 1920, b.y0 * 1080], [b.x1 * 1920, b.y0 * 1080],
             [b.x1 * 1920, b.y1 * 1080], [b.x0 * 1920, b.y1 * 1080]], drawn))
    return dets


def _dora_dets(markers):
    from majsoul_eye.coords import dora_slot
    dets = []
    for i, p in enumerate(markers):
        b = dora_slot(i)
        dets.append(_det_from_poly(
            [[b.x0 * 1920, b.y0 * 1080], [b.x1 * 1920, b.y0 * 1080],
             [b.x1 * 1920, b.y1 * 1080], [b.x0 * 1920, b.y1 * 1080]], p))
    return dets


def test_river_last_row_hole_flags_violation():
    # 8-tile river missing tile #7 (first tile of row 1): the surviving row-1
    # tile sits one pitch off the row origin — must be flagged, not silently
    # returned as a shorter river with wrong order. Final-review probe.
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    dets = _river_dets(0, ["1m", "9p", "E", "5sr", "2s", "7p", "C", "3m"])
    del dets[6]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _assign_river(0, items)
    assert viol


def test_river_mid_row_hole_flags_violation():
    # 4-tile river missing tile #2: rows 0-only, cross-row prefix check can't
    # see it; the within-row gap (2x pitch) must. Final-review probe.
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    dets = _river_dets(0, ["1m", "9p", "E", "2s"])
    del dets[1]
    items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
    _, viol = _assign_river(0, items)
    assert viol


def test_full_frame_roundtrip():
    from majsoul_eye.recognize.assemble import assemble
    hand = ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m", "1p"]
    dets = _hand_dets(hand, drawn="4p")
    dets += _dora_dets(["5s"])
    dets += _river_dets(0, ["9p", "1s"])
    dets += _river_dets(1, ["E", "W", "N"], sideways_idx=1)
    dets += _river_dets(2, ["S"])
    dets += _river_dets(3, ["C", "9s"])
    dets += _meld_dets(0, [_gt("pon", ["P", "P", "P"], called="P",
                               from_seat_rel=2, seat=0)])
    dets += _meld_dets(2, [_gt("ankan", ["F", "F", "F", "F"], seat=2)])
    # a stray opponent-hand back must be dropped silently: backs never route to
    # river zones (measured: this point is only ~53px from seat-0's river frame,
    # inside the 60px cutoff — the back-only-melds rule is what excludes it),
    # and its meld distance is far beyond the cutoff
    dets.append(_det_from_poly([[940, 510], [980, 510], [980, 570], [940, 570]],
                               "back"))
    o = assemble(dets, REGION)
    assert o.violations == []
    assert o.hero_hand == hand and o.drawn_tile == "4p"
    assert o.dora_markers == ["5s"]
    assert [t.pai for t in o.rivers[1]] == ["E", "W", "N"]
    assert o.rivers[1][1].sideways and o.reach == [False, True, False, False]
    assert o.melds[0][0].type == "pon" and o.melds[0][0].from_rel == 2
    assert o.melds[2][0].type == "ankan"
    assert o.zone_confidence["hand"] > 0


def test_river_hbb_fallback():
    # HBB models carry no poly; _fw_points falls back to the xyxy box corners.
    # Order + sideways must still recover (sideways = warped extent ratio, which
    # an axis-aligned box preserves). Final-review coverage item: every other
    # river/meld test goes through the OBB poly path.
    from dataclasses import replace
    from majsoul_eye.recognize.assemble import _assign_river, _fw_points
    for seat in range(4):
        dets = [replace(d, poly=None)
                for d in _river_dets(seat, ["1m", "9p", "E", "5s"], sideways_idx=2)]
        items = [(d, _fw_points(d, REGION, H["H_full"])) for d in dets]
        out, viol = _assign_river(seat, items)
        assert not viol, (seat, viol)
        assert [t.pai for t in out] == ["1m", "9p", "E", "5s"], seat
        assert out[2].sideways and not out[0].sideways, seat


def test_hud_class_detections_ignored():
    # 56-class weights emit HUD detections (tile=None: scores, wall count,
    # reach sticks, buttons). Tile assembly must skip them entirely — they are
    # assemble_hud's domain. Regression: they used to route as tiles, producing
    # "stray detection None" violations (far boxes) or corrupting a meld-strip
    # parse (near boxes like a reach stick), rejecting every real frame.
    from majsoul_eye.hud import DET_NAMES
    from majsoul_eye.recognize.assemble import assemble
    hand = ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
            "1p", "2p", "3p", "4p"]
    dets = _hand_dets(hand) + _dora_dets(["5s"]) + _river_dets(0, ["9p", "1s"])
    dets += _meld_dets(2, [_gt("pon", ["P", "P", "P"], called="P",
                               from_seat_rel=2, seat=2)])
    base = assemble(list(dets), REGION)
    assert base.violations == []

    def hud_det(name, box):
        (x0, y0), (x1, y1) = box
        return Detection(xyxy=(x0, y0, x1, y1), name=name, tile=None,
                         cls=DET_NAMES.index(name), score=0.9,
                         poly=((x0, y0), (x1, y0), (x1, y1), (x0, y1)))

    dets.append(hud_det("score_self", ((880, 620), (1040, 660))))   # far off-zone
    dets.append(hud_det("wall_count", ((760, 460), (820, 500))))    # center panel
    dets.append(hud_det("reach_stick", ((900, 430), (1020, 445))))  # near the felt zones
    o = assemble(dets, REGION)
    assert o.violations == []
    assert o.hero_hand == base.hero_hand
    assert [t.pai for t in o.rivers[0]] == [t.pai for t in base.rivers[0]]
    assert o.melds[2][0].type == "pon"


def test_standing_concealed_backs_filtered_from_meld_strips():
    # Backs-trained weights (2026-07-09) detect opponents' STANDING concealed
    # hands; 10+ of those backs per seat land inside the meld-strip 60px window
    # and used to make every strip unparsable (949/949 frames rejected).
    # Discriminator: a standing tile's perspective smear (screen-vertical)
    # maps to the strip's ALONG axis for side strips (seats 1/3) and CROSS
    # axis for the far strip (seat 2) — measured lying<=96 vs standing>=120
    # fullwarp units against d~92. Ankan lying backs must survive
    # (test_meld_parse_kans covers that side).
    import numpy as np, cv2
    from majsoul_eye.recognize.assemble import assemble
    hand = ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
            "1p", "2p", "3p", "4p"]
    dets = _hand_dets(hand) + _dora_dets(["5s"]) + _river_dets(0, ["9p"])
    base = assemble(list(dets), REGION)
    assert base.violations == []
    Hinv = np.linalg.inv(H["H_full"])
    for seat in (1, 2, 3):
        cfg = P.MELD_STRIP2[seat]
        corner = np.array(cfg["corner"], dtype=float)
        u, v = np.array(cfg["along"], dtype=float), np.array(cfg["cross"], dtype=float)
        smear = 1.5 * cfg["d"]
        ea, ec = ((smear, 0.75 * cfg["d"]) if seat in (1, 3)
                  else (cfg["w"], smear))          # (ext_along, ext_cross)
        for i in range(3):
            fw = np.float32([corner + u * (i * cfg["w"]) + v * 0,
                             corner + u * (i * cfg["w"] + ea) + v * 0,
                             corner + u * (i * cfg["w"] + ea) + v * ec,
                             corner + u * (i * cfg["w"]) + v * ec])
            quad = cv2.perspectiveTransform(fw[None], Hinv.astype(np.float64))[0]
            dets.append(_det_from_poly(quad.tolist(), "back"))
    o = assemble(dets, REGION)
    assert o.violations == []
    assert all(o.melds[s] == [] for s in (1, 2, 3))


def test_meld_sideways_by_edge_orientation_not_extents():
    # Regression fixture from a real off-domain screenshot (samples/1.png,
    # 2302x1288 phone capture): seat2 strip with two chis (1p2p3p + 5m6m7m).
    # Upright cells' warped OBBs are near-square (ext_along 99-101 vs
    # ext_cross 92), so the old ext_a > ext_c rule judged 4 upright cells
    # sideways and the strip became unparsable. The OBB's own LONG-EDGE
    # direction separates cleanly (upright long edge ~93 runs cross-wise,
    # sideways ~103 runs along) and must be the discriminator.
    import numpy as np
    from majsoul_eye.recognize.assemble import _parse_melds

    class _D:  # _parse_melds only reads .tile
        def __init__(self, tile): self.tile = tile

    quads = [
        ("2p", [[767.1, 220.6], [752.2, 128.4], [665.8, 128.3], [682.4, 220.6]]),
        ("1p", [[836.3, 220.7], [822.7, 128.4], [737.1, 128.4], [752.3, 220.6]]),
        ("3p", [[924.6, 198.1], [915.7, 128.3], [813.1, 128.3], [823.5, 198.1]]),
        ("7m", [[996.8, 220.7], [986.2, 128.0], [903.6, 128.1], [915.8, 220.9]]),
        ("5m", [[1066.1, 220.5], [1056.9, 127.9], [975.4, 128.0], [986.2, 220.7]]),
        ("6m", [[1154.8, 198.1], [1149.2, 128.5], [1049.8, 128.6], [1056.8, 198.2]]),
    ]
    items = [(_D(t), np.float32(q)) for t, q in quads]
    melds, viol = _parse_melds(2, items)
    assert viol == [], viol
    assert [(m.type, tuple(m.tiles), m.called_pai) for m in melds] == \
        [("chi", ("1p", "2p", "3p"), "3p"), ("chi", ("5m", "6m", "7m"), "6m")]


def test_wide_frame_dora_rescued_from_screen_corner():
    # Ultrawide phone screenshots (2.17:1): the 3D table is a centered 16:9
    # rect but the dora indicator is 2D HUD anchored near the SCREEN's
    # top-left corner — outside the board rect, at a device-dependent inset
    # (iPhone safe-area differs from Android), so no fixed box works. Rescue:
    # after zone routing, stray TILE detections forming a horizontal row in
    # the screen's top-left region are the dead-wall dora row.
    from majsoul_eye.normalize import BoardRegion
    from majsoul_eye.recognize.assemble import assemble
    ox, scale = 261, 2346 / 1920.0          # board rect of a 2868x1320 frame
    region_w = BoardRegion(ox, 0, 2346, 1320, 2868, 1320)

    def widen(d):
        x0, y0, x1, y1 = d.xyxy
        poly = tuple((px * scale + ox, py * scale) for px, py in d.poly)
        from dataclasses import replace
        return replace(d, xyxy=(x0 * scale + ox, y0 * scale, x1 * scale + ox,
                                y1 * scale), poly=poly)

    hand = ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
            "1p", "2p", "3p", "4p"]
    dets = [widen(d) for d in _hand_dets(hand) + _river_dets(0, ["9p"])]
    # dora row at the real iPhone-sample position: marker 6m + a back,
    # left of the board rect (x < 261+), one horizontal row
    dets.append(_det_from_poly([[221, 78], [290, 78], [290, 176], [221, 176]], "6m"))
    dets.append(_det_from_poly([[289, 77], [359, 77], [359, 176], [289, 176]], "back"))
    o = assemble(dets, region_w)
    assert o.violations == []
    assert o.dora_markers == ["6m"]
    assert o.hero_hand == hand


def test_full_frame_feeds_reconstruct():
    from majsoul_eye.recognize.assemble import assemble
    from majsoul_eye.state.reconstruct import reconstruct
    hand = ["1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m", "1p", "2p", "3p", "4p"]
    dets = _hand_dets(hand) + _dora_dets(["5s"])
    dets += _river_dets(0, ["9p"]) + _river_dets(1, ["E"]) + _river_dets(2, ["S"])
    o = assemble(dets, REGION)
    assert o.violations == []
    r = reconstruct(o)
    assert r.ok, r.reason


# --- HUD fill via hud_reader (spec 2026-07-09 §1/§2) --------------------------
import numpy as np

from majsoul_eye.hud import DET_NAMES
from majsoul_eye.normalize import locate_fullscreen
from majsoul_eye.recognize.assemble import assemble
from majsoul_eye.recognize.detector import Detection
from majsoul_eye.tiles import TILE_NAMES


def _D(name, box):
    cls = DET_NAMES.index(name)
    return Detection(xyxy=tuple(float(v) for v in box), name=name,
                     tile=name if cls < len(TILE_NAMES) else None,
                     cls=cls, score=0.9)


class _StubReader:
    def __init__(self, answers): self.answers = answers
    def read(self, crop, cls): return self.answers[cls]


_frame = np.zeros((1080, 1920, 3), np.uint8)
_region = locate_fullscreen(_frame)
_hud_dets = [
    _D("round_label", (905, 350, 1015, 385)),
    _D("wall_count", (925, 385, 995, 415)),
    _D("score_self", (900, 460, 1000, 500)), _D("score_right", (1030, 400, 1080, 470)),
    _D("score_across", (900, 300, 1000, 340)), _D("score_left", (840, 400, 890, 470)),
    _D("riichi_stick_count", (200, 60, 280, 100)), _D("honba_count", (235, 135, 315, 185)),
    _D("seat_wind_self", (830, 470, 890, 530)),
    _D("btn_riichi", (1200, 740, 1360, 790)),
    _D("reach_stick", (900, 500, 1020, 530)),      # below anchor -> rel seat 0 (self)
]
_reader = _StubReader({"round_label": "S3", "wall_count": "余42",
                       "score_self": "24000", "score_right": "31000",
                       "score_across": "20000", "score_left": "24000",
                       "riichi_stick_count": "x1", "honba_count": "x2",
                       "seat_wind_self": "W"})

o = assemble(_hud_dets, _region, frame_bgr=_frame, hud_reader=_reader)
assert o.bakaze == "S" and o.kyoku == 3
assert o.left_tile_count == 42 and o.kyotaku == 1 and o.honba == 2
assert o.scores == [24000, 31000, 20000, 24000]
assert o.seat_wind_self == "W"
assert o.pending_buttons == ["btn_riichi"]
assert o.reach == [True, False, False, False]      # stick below anchor -> self
assert "hud" in o.zone_confidence

# graceful degrade: no reader -> HUD detections dropped, fields stay None
o2 = assemble(_hud_dets, _region)
assert o2.scores is None and o2.bakaze is None and o2.pending_buttons is None
assert o2.reach == [False] * 4 and "hud" not in o2.zone_confidence

# partial scores (one seat unread) -> whole scores list stays None
_bad = _StubReader({**_reader.answers, "score_left": ""})
o3 = assemble(_hud_dets, _region, frame_bgr=_frame, hud_reader=_bad)
assert o3.scores is None and o3.kyoku == 3         # other fields still fill

print("test_assemble hud fill OK")


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_"):
            fn()
    print("test_assemble OK")
