"""Opponent concealed-hand (牌背) auto-annotation — EXPERIMENTAL (手摸切 groundwork).

Boxes the three opponents' concealed hand-row tile backs from GT alone: the row
tile count is known (``BoardState.concealed_counts``), the per-tile geometry is a
MANUALLY CLICKED template set (``_backs_manual.py`` — generated by
``scripts/annotate/calibrate_backs_manual.py --ingest`` from 4-corner clicks on
real run_8 frames, mapped to fullwarp px). Class is the existing 38-class
``back`` — no new detector head id.

Opt-in only (``annotate_frame(..., backs=True)``; ``build_datasets.py --backs``):
this is the training groundwork for tedashi/tsumogiri (手切/摸切) recognition —
a detector that finds each back individually lets downstream logic read a
mid-discard row GAP as a missing detection. NOT part of the default v1/v2 sets.

Geometry model (manual templates, 2026-07-07; earlier automatic strip-run fit
kept below in BACK_ROWS as the coarse reference — see STATUS.md §1.45):
  * BACK_SLOT_QUADS[pos][i] = fullwarp quad of row slot i; slot 0 is the
    ANCHORED end (player's left), which stays put as melds shrink the row.
    Template centroid pitch came out 71.1/71.3/71.2 for the three seats —
    physically one tile width, a strong self-consistency check vs the automatic
    sprite-extent pitches (76.9/72.6/78.2) that averaged the lean smear in.
  * melds: the concealed row is simply the first ``row_n`` template slots at
    their FIXED positions — no re-spacing (tiles are laid from the anchor at a
    fixed pitch, a meld just drops the far slots). ``_meld_k`` is 1.0 (meld_bias
    all 0); the earlier per-seat stretch was a sprite-extent artifact that
    drifted short rows off their moving end (STATUS §1.49).
  * BACK_DRAWN_QUADS[pos] = the separated drawn-tile slot, clicked on real
    first-turn thinking frames (centroid gap beyond slot 12 ≈ +36 px, identical
    across all three seats). For a melded/short row it rides the moving end via
    ``_drawn_fw`` (validated on real 0-meld and 1-meld holding frames).
  * a HOLDING seat (concealed_count % 3 == 2 — just drew, drawn tile still up)
    IS LABELED: the concealed row is a STATIC ``n-1``-tile row (the draw does not
    reflow it) plus one separated drawn-tile back. Both are fully GT-derivable —
    the row is the same templates, the drawn tile sits in the fixed drawn slot
    (STATUS §1.46, correcting the earlier belief that holding was underivable;
    that reasoning actually belonged to the POST-tedashi reflow, which the
    ``sorting_suspect`` pixel gate handles on settled frames). The slide-in
    draw animation can in principle leave the drawn tile unrendered for a
    beat; the debounce-to-quiet capture sync makes that residual rare, and no
    per-box pixel gate covers it since the fill gate was removed (2026-07-10 —
    it had zero discriminative power on these edge-on rows; ``fill`` is now a
    QA diagnostic only).
"""
from __future__ import annotations

import cv2
import numpy as np

from majsoul_eye.annotate import pipeline as P
from majsoul_eye.annotate._backs_manual import BACK_DRAWN_QUADS, BACK_SLOT_QUADS

# Coarse per-seat row model from the AUTOMATIC strip-run calibration (run_8
# games 1-4, V>170 fullwarp runs, mad=0 per extent). The manual templates above
# supersede it for box geometry; this stays as (a) the along-axis/anchor-side
# metadata, (b) the reference the ingest validation prints against.
# ``meld_bias`` is 0 for every seat: a melded row is simply the first row_n
# TEMPLATE slots at their fixed positions — the concealed tiles are laid from the
# anchor at a fixed pitch, so removing tiles (a meld) drops the far slots and does
# NOT re-space the rest. The earlier non-zero biases (17/0/25.5) came from fitting
# the moving-end SPRITE EXTENT (lean smear), which over-stretched short rows and
# drifted the boxes toward the moving end (~+3.6% on pos3 -> last box off the row
# end; user-spotted on a pos3 1-meld frame, STATUS §1.49). Verified k=1 hugs every
# tile on 1-meld rows for all three seats.
BACK_ROWS = {
    1: {"along": "y", "along0": 587.0, "along1": 1587.0, "pitch": 76.92,
        "cross": (2380.0, 2505.0), "anchor": "high", "meld_bias": 0.0},
    2: {"along": "x", "along0": 1179.0, "along1": 2123.0, "pitch": 72.62,
        "cross": (50.0, 230.0), "anchor": "high", "meld_bias": 0.0},
    3: {"along": "y", "along0": 277.0, "along1": 1293.0, "pitch": 74.08,
        "cross": (552.0, 692.0), "anchor": "low", "meld_bias": 0.0},
}
DRAWN_GAP = 25.0        # fullwarp px, sprite-run edge gap (manual centroid gap ≈ 36)


def _axis(pos: int) -> int:
    return 0 if BACK_ROWS[pos]["along"] == "x" else 1


def _anchor_coord(pos: int) -> float:
    """Along-coordinate of the row's anchored extreme (player's-left edge)."""
    ai = _axis(pos)
    vals = [p[ai] for q in BACK_SLOT_QUADS[pos] for p in q]
    return max(vals) if BACK_ROWS[pos]["anchor"] == "high" else min(vals)


def _tpl_pitch(pos: int) -> float:
    """Template centroid pitch (≈71.2 everywhere; per-seat for exactness)."""
    ai = _axis(pos)
    tpl = BACK_SLOT_QUADS[pos]
    c0 = sum(p[ai] for p in tpl[0]) / 4.0
    c12 = sum(p[ai] for p in tpl[12]) / 4.0
    return abs(c12 - c0) / 12.0


def _stretch_quad(quad, pos: int, k: float):
    """Scale a fullwarp quad's along-coordinates about the row anchor by k."""
    if k == 1.0:
        return [list(map(float, p)) for p in quad]
    ai = _axis(pos)
    a = _anchor_coord(pos)
    out = []
    for p in quad:
        q = [float(p[0]), float(p[1])]
        q[ai] = a + (q[ai] - a) * k
        out.append(q)
    return out


def _meld_k(pos: int, row_n: int, n_melds: int) -> float:
    """About-anchor stretch for a melded row. Now identically 1.0 for every seat
    (meld_bias all 0 — a melded row does not re-space; see module doc / BACK_ROWS
    comment). Kept as a hook so a future measured re-spacing, if any, drops in via
    meld_bias without touching call sites."""
    if not n_melds or not BACK_ROWS[pos]["meld_bias"]:
        return 1.0
    return 1.0 + (n_melds * BACK_ROWS[pos]["meld_bias"]) / (row_n * _tpl_pitch(pos))


def generate_back_boxes(pos: int, row_n: int, n_melds: int, H_full_inv) -> list:
    """Per-slot boxes for a SETTLED (non-holding) opponent hand row.

    Returns [{tile:"back", slot, poly_fullwarp, poly_original}] ordered from the
    anchored (player's left) end. row_n outside 1..13 yields [] (caller flags).
    """
    if not (1 <= row_n <= 13) or pos not in BACK_SLOT_QUADS:
        return []
    k = _meld_k(pos, row_n, n_melds)
    out = []
    for i in range(row_n):
        quad_fw = _stretch_quad(BACK_SLOT_QUADS[pos][i], pos, k)
        quad_or = P.fullwarp_to_original(quad_fw, H_full_inv)
        out.append({"tile": "back", "slot": i,
                    "poly_fullwarp": [[round(float(x), 1) for x in p] for p in quad_fw],
                    "poly_original": [[round(float(x), 1) for x in p] for p in quad_or]})
    return out


def _drawn_fw(pos: int, row_n: int, n_melds: int, extra_pitches: float = 0.0):
    """Fullwarp quad of the separated drawn-tile slot for a row_n-tile row (it
    rides the moving end), optionally shifted further from the anchor by
    `extra_pitches` tile widths (used to sample an empty-felt reference)."""
    ai = _axis(pos)
    a = _anchor_coord(pos)
    tpl = BACK_SLOT_QUADS[pos]
    outer_full = max(abs(p[ai] - a) for p in tpl[12])
    outer_now = max(abs(p[ai] - a) for p in
                    _stretch_quad(tpl[row_n - 1], pos, _meld_k(pos, row_n, n_melds)))
    sign = -1.0 if BACK_ROWS[pos]["anchor"] == "high" else 1.0
    # sign*(outer_now-outer_full) rides the moving end toward the anchor for short
    # rows; +sign*extra*pitch moves AWAY from the anchor (past the drawn slot).
    shift = sign * (outer_now - outer_full) + sign * (extra_pitches * _tpl_pitch(pos))
    out = []
    for p in BACK_DRAWN_QUADS[pos]:
        q = [float(p[0]), float(p[1])]
        q[ai] += shift
        out.append(q)
    return out


def drawn_quad(pos: int, row_n: int, n_melds: int, H_full_inv):
    """Separated drawn-tile quad in ORIGINAL px — used by the holding-state label
    (the concealed row's separated tile) and the sorting gate below."""
    return P.fullwarp_to_original(_drawn_fw(pos, row_n, n_melds), H_full_inv)


def _drawn_box(pos: int, row_n: int, n_melds: int, H_full_inv) -> dict:
    """The separated drawn-tile back box for a holding row (slot index = row_n,
    i.e. appended after the row's 0..row_n-1 slots). ``drawn`` marks it for QA."""
    quad_fw = _drawn_fw(pos, row_n, n_melds)
    quad_or = P.fullwarp_to_original(quad_fw, H_full_inv)
    return {"tile": "back", "slot": row_n, "drawn": True,
            "poly_fullwarp": [[round(float(x), 1) for x in p] for p in quad_fw],
            "poly_original": [[round(float(x), 1) for x in p] for p in quad_or]}


def _patch_stats(img: np.ndarray, quad_orig) -> tuple | None:
    """(gray mean, gray std) over the quad's bbox, None if degenerate/off-frame."""
    p = np.float32(quad_orig)
    x0, y0 = max(0, int(p[:, 0].min())), max(0, int(p[:, 1].min()))
    x1, y1 = min(img.shape[1], int(p[:, 0].max())), min(img.shape[0], int(p[:, 1].max()))
    if x1 - x0 < 4 or y1 - y0 < 4:
        return None
    g = cv2.cvtColor(img[y0:y1, x0:x1], cv2.COLOR_BGR2GRAY)
    return float(g.mean()), float(g.std())


def sorting_suspect(img: np.ndarray, pos: int, row_n: int, n_melds: int, H_full_inv) -> bool:
    """Post-tedashi 理牌 (row-compaction) gate for a GT-SETTLED row.

    After an opponent discards from hand the client re-compacts the row
    (~0.5-1s) while GT is already settled; the capture stability ROI
    (roi_diff.TABLE_ROI) does NOT cover the hand rows, so canonical frames can
    catch the compaction mid-flight — template boxes then misalign. Signature:
    some ROW SLOT reads as bare felt (the pulled tile's gap, open mid-row or
    at the anchor-far end after closing). Patches are classified by (gray
    mean, std) distance to the row's own tile median vs an empty-felt
    reference sampled 1.15 tiles past the drawn slot — relative comparisons
    survive skins. Fires on 0.4-3% of settled seat-frames (the real reflow
    rate).

    A second signature ("the 13-row DRAWN slot reads occupied", Condition B of
    STATUS §1.48) was REMOVED 2026-07-10: its patch straddles the last-tile
    edge, and on dark skins the row's tile median ≈ that edge mean, so it
    false-fired on ~100% of skinned settled rows (253/256 firings on
    ai_session4/run_5/game1) and 17.6% of eligible frames dataset-wide —
    each one a WHOLE-FRAME drop in build_dataset (the largest frame-drop
    cause in the pipeline; see spec 2026-07-10)."""
    k = _meld_k(pos, row_n, n_melds)
    slots = [_patch_stats(img, P.fullwarp_to_original(
        _stretch_quad(BACK_SLOT_QUADS[pos][i], pos, k), H_full_inv)) for i in range(row_n)]
    slots = [s for s in slots if s]
    empty = _patch_stats(img, P.fullwarp_to_original(_drawn_fw(pos, row_n, n_melds, 1.15), H_full_inv))
    if len(slots) < 3 or empty is None:
        return False
    tm = (float(np.median([s[0] for s in slots])), float(np.median([s[1] for s in slots])))

    def dist(a, b):
        return abs(a[0] - b[0]) + abs(a[1] - b[1])

    return any(dist(s, empty) < 0.7 * dist(s, tm) for s in slots)


def back_boxes(img: np.ndarray, state, hom: dict):
    """(rec_dict, flags) for all three opponent seats of one frame.

    rec_dict maps str(pos) -> box list (empty for skipped seats). ``fill``
    (tile_live_mask coverage of the original-px bbox) is recorded as a QA
    diagnostic only. It does NOT gate reliability: for these edge-on rows the
    skewed quad's bbox is mostly felt, and every mahjong felt is colored or
    bright, so empty felt reads 1.00 on every table while a dark skinned back
    reads 0.24 — the positive class scores BELOW the negative and no threshold
    separates them (measured 2026-07-10; the mask stays valid in the dora/meld
    role it was calibrated for). GT-leads-render protection comes from
    is_deal_window / is_call_window (whole-frame drops) and sorting_suspect
    (Condition A).
    """
    from majsoul_eye.annotate.seatgt import _screen_to_seat, SEAT_POS

    Hinv = hom["H_full_inv"]
    live = P.tile_live_mask(img)
    ii = cv2.integral(live)
    rec, flags = {}, []
    for pos in (1, 2, 3):
        seat = _screen_to_seat(state.hero_seat, SEAT_POS[pos])
        if seat is None:
            rec[str(pos)] = []
            continue
        n = state.concealed_counts[seat]
        n_melds = len(state.melds[seat])
        holding = (n % 3 == 2)               # just drew, drawn tile still up
        row_n = n - 1 if holding else n      # the concealed ROW omits the drawn tile
        if not (1 <= row_n <= 13):
            rec[str(pos)] = []
            if row_n:
                flags.append(f"pos{pos}:backs_bad_row_n={row_n}")
            continue
        # Post-tedashi 理牌 reflow only happens on SETTLED rows (after a discard);
        # a holding row is static (the draw slides in the separate tile, not the
        # row), so the reflow gate is settled-only.
        if not holding and sorting_suspect(img, pos, row_n, n_melds, Hinv):
            rec[str(pos)] = []
            flags.append(f"pos{pos}:backs_sorting")
            continue
        boxes = generate_back_boxes(pos, row_n, n_melds, Hinv)
        if holding:                          # + the separated drawn-tile back
            boxes.append(_drawn_box(pos, row_n, n_melds, Hinv))
        for b in boxes:
            p = np.float32(b["poly_original"])
            f = P._box_fill(ii, p[:, 0].min(), p[:, 1].min(), p[:, 0].max(), p[:, 1].max())
            b["fill"] = round(float(f), 3)   # diagnostic only, never gates (see docstring)
        rec[str(pos)] = boxes
    return rec, flags
